export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export const START_MEDIA_LOADING = 'START MEDIA LOADING';
export const STOP_MEDIA_LOADING = 'STOP MEDIA LOADING';
export const START_IMAGES_LOADING = 'START IMAGES LOADING';
export const STOP_IMAGES_LOADING = 'STOP IMAGES LOADING';
export const START_POPUP_LOADING = 'START POPUP LOADING';
export const STOP_POPUP_LOADING = 'STOP POPUP LOADING';

export const SHOW_POPUP = 'SHOW_POPUP';
export const HIDE_POPUP = 'HIDE_POPUP';

export const ACTIVATE_LOGO_MENU = 'ACTIVATE_LOGO_MENU';
export const DEACTIVATE_LOGO_MENU = 'DEACTIVATE_LOGO_MENU';

export const UPDATE_HOME_MEDIA_IMAGE = 'UPDATE_HOME_MEDIA_IMAGE';

export const UPDATE_WORK_MEDIA_LOCATION = 'UPDATE_WORK_MEDIA_LOCATION';
