export const LOCATION_UPDATED = 'LOCATION_UPDATED';

export const MEDIA_LOADING_STARTED = 'MEDIA_LOADING_STARTED';
export const MEDIA_LOADING_STOPPED = 'MEDIA_LOADING_STOPPED';
export const IMAGES_LOADING_STARTED = 'IMAGES_LOADING_STARTED';
export const IMAGES_LOADING_STOPPED = 'IMAGES_LOADING_STOPPED';
export const POPUP_LOADING_STARTED = 'POPUP_LOADING_STARTED';
export const POPUP_LOADING_STOPPED = 'POPUP_LOADING_STOPPED';

export const POPUP_SHOWED = 'POPUP_SHOWED';
export const POPUP_HIDDEN = 'POPUP_HIDDEN';

export const LOGO_MENU_ACTIVATED = 'LOGO_MENU_ACTIVATED';
export const LOGO_MENU_DEACTIVATED = 'LOGO_MENU_DEACTIVATED';

export const HOME_MEDIA_IMAGE_UPDATED = 'HOME_MEDIA_IMAGE_UPDATED';

export const WORK_MEDIA_LOCATION_UPDATED = 'WORK_MEDIA_LOCATION_UPDATED';
